# Generated by Django 3.1.1 on 2020-10-03 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0003_auto_20201003_1556'),
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='field',
            options={'verbose_name': 'Field', 'verbose_name_plural': 'Fields'},
        ),
        migrations.AlterModelOptions(
            name='journal',
            options={'verbose_name': 'Journal', 'verbose_name_plural': 'Journals'},
        ),
        migrations.AlterModelOptions(
            name='university',
            options={'verbose_name': 'University', 'verbose_name_plural': 'Universities'},
        ),
        migrations.AlterField(
            model_name='paper',
            name='legacy_users',
            field=models.ManyToManyField(blank=True, related_name='papers', to='user.LegacyUser'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='papers', to='resume.resume'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='papers', to=settings.AUTH_USER_MODEL),
        ),
    ]
